# Generated by Django 5.1.7 on 2025-05-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ordered_date',
            new_name='order_date',
        ),
    ]
